### ISSUE TITLE
Problem giving jester kit to Imoen

### ISSUE THREAD

**Issue by IceLancerSR** [subtledoctor/NPC_EE#4]
ignore imoen, i hacked script a bit to add bard when it was reading thief.still dont know why it was reading thief in first place tho.
P.S
jaheira didn't change to single class druid.
i also left Viconia as default pure cleric. Installed priest of tempus kit.But she has no options to change into one at all.button is greyed out.
possible that tempust doesnt work properly with sod?

P.S
Playing BG EE SOD
Tested on clean game with kits and this mod only.

**Comment by IceLancerSR** [comment]
AAAH.. finally found why imoen kept getting thief kits instead of bard..
spell D5_THKT didnt get removed/replaced with D5_BAKT,so it kept reading thief and not bard..

Maybe wanna add that for future in script ,once class is changed it should update spell as well

**Comment by subtledoctor** [comment]
This should be fixed as of the latest version (2.6 I think)
